### ISSUE TITLE
Style Points using Images

### ISSUE THREAD

**Issue by Treemeister** [xordspar0/Data61-capstone-2016#17]

**Comment by xordspar0** [comment]
We're looking at how to display multiple icons side-by-side so we can visualize multiple route evaluation criteria at once, but we're not sure of the best way to do this right now.

One option is to just put down one point for each criteria, each with its own icon to visualize a different criteria. Problems with doing this are that we would need to figure out where to place each point on the map, and the spacing between the points would be static: if your zoom way out, the points would all squish together, and if you zoom out, the points would be far apart.

Another option is to have one icon visible for each route at first. This would be an overall evaluation of the route. When the user clicks on this icon, a description would pop up that gives details about why the route was evaluated the way it was and ratings of all the individual criteria.

**Comment by imanavaz** [comment]
A work around would be to provide a panel on the side, so the user can choose which categories are of interest. Selecting the required categories will affect which points get displayed on the path. 

Another approach would be to use visualizations to abstractly indicate the "goodness" of the path. For example use strokes and color to show the goodness, and if user wants, they can select the option of showing the actual points of interest. So with this, user can see which paths is better (for example the green thick one!) and to see why it is better, choose the option and see the points on the path to drill down. 

With Strokes/color you could use twisting lines to show multi categories (I would very much like to see this one if possible to implement!)
