### ISSUE TITLE
Most of the Flickr photos have "undefined" coordinates

### ISSUE THREAD

**Issue by xordspar0** [xordspar0/Data61-capstone-2016#25]
If you look at the resulting KML file after adding the Flickr photos, only 1 or 2 of the 250 or so photos have latitude and longitude coordinates. I think there is a problem with the way I am doing the location API calls in dataSources.js. It might need to be paralellized somehow.

**Comment by imanavaz** [comment]
If the problem proved hard to solve, use the prepared datasets from [here](https://webscope.sandbox.yahoo.com/catalog.php?datatype=i&did=67). Dongwoo has written some py code to extract data for melbourne from this dataset [here](https://github.com/arongdari/flickr-photo)
