### ISSUE TITLE
Do a simple demo visualization

### ISSUE THREAD

**Issue by xordspar0** [xordspar0/Data61-capstone-2016#5]

**Comment by xordspar0** [comment]
@Treemeister and I are working on this.

**Comment by xordspar0** [comment]
Step 1 is in fa975ef0706d64c27e6327ffb1bce00ed671b9d0

**Comment by xordspar0** [comment]
In 82f62e5d1e2fa8b0ac27b4e254e23f30beb3f738, I made a demo showing styles working in KML.

In 1af10ff72fba307af1a343f9eb3c9999f36ebfe0, I made a mock-up of what route visualizations might look like using KML.

**Comment by imanavaz** [comment]
Looks very good guys. Just consider that google maps API allows certain number of points for route calculation. You will need to find a workaround.

Your next step would be to find out how to export this.
